language: node_js
node_js:
- 8.9
before_install:
- openssl aes-256-cbc -K $encrypted_16130f077f6a_key -iv $encrypted_16130f077f6a_iv
  -in id_rsa.enc -out ~\/.ssh/id_rsa -d
install:
  - npm install
  - npm run build --prod
