language: php

php:
  - 7.2

before_install:
- openssl aes-256-cbc -K $encrypted_8cc84dc4d66a_key -iv $encrypted_8cc84dc4d66a_iv -in id_rsa.enc -out ~/.ssh/id_rsa -d
- chmod 600 ~/.ssh/id_rsa
- export DOCKER_ID_USER="$docker_user"

install:
- cp .env.example .env
- docker run --rm -it --volume $(pwd):/app prooph/composer:7.2 install
- docker run --rm -it --volume $(pwd):/app -w /app --entrypoint php prooph/composer:7.2 artisan key:generate
- docker build -t lua-china-admin:0.1 .
- docker login -u $docker_user -p $docker_password
- docker tag lua-china-admin:0.1 $DOCKER_ID_USER/lua-china-admin:0.1
- docker push $DOCKER_ID_USER/lua-china-admin:0.1
- ssh -o "StrictHostKeyChecking no" root@115.28.82.133 "(docker rm -f lua-china-admin || true) && (docker rmi -f horan/lua-china-admin:0.1 || true)"
- ssh -o "StrictHostKeyChecking no" root@115.28.82.133 "docker run -p 10.31.231.178:8001:80 --name=lua-china-admin -d horan/lua-china-admin:0.1"

after_success:
 - rm -rf ~/.ssh
