version: '2.1'
services:
    nginx:
        image: nginx:latest
        ports:
          - 8001:80
        volumes:
            - ./:/app
            # nginx configs
            - ./docker/nginx/conf/nginx.conf:/etc/nginx/nginx.conf
    php-fpm:
        build: ./docker/php-fpm
        volumes:
            - ./:/app
    php-composer:
        restart: 'no'
        image: composer
        volumes:
            - ./:/app
        command: install
    nodejs:
        restart: 'no'
        image: node:8.9
        volumes:
            - ./:/app
        command: /bin/bash -c "cd /app && npm install && npm run prod"
networks:
  default: